### ISSUE TITLE
organization must disable OAuth App access restrictions

### ISSUE THREAD

**Issue by rogi-rogi** [likelionknu/calendar-react-frontend#3]
`likelionknu` organization has enabled OAuth App access restrictions
plz remove restrictions

https://docs.github.com/ko/organizations/managing-oauth-access-to-your-organizations-data/disabling-oauth-app-access-restrictions-for-your-organization

**Comment by rogi-rogi** [comment]
ACCESS_LIMITED - Although you appear to have the correct authorization credentials, the `likelionknu` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit

https://docs.github.com/articles/restricting-access-to-your-organization-s-data/ (500)

**Comment by klmhyeonwoo** [comment]
Solve
